### ISSUE TITLE
Define a minimum metadata model design for GDI

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-docs#3]
## Assumptions
the GDI metadata standard will be based on DCAT (and related) vocabularies and will be an implementation of the European DCAT-AP (Application Profile). More information can be found at: https://op.europa.eu/nl/web/eu-vocabularies/dcat-ap

## What
Define a minimum metadata model design for GDI.
- applying stepping stone principle and start with the bare minimum (DCAT-AP core)
- extend it with petals per use case (to build the sunflower) using the current confirmed minimal datasets from 1+MG
- follow the EHDS2-pilot that works on the Health DCAT-AP

Document and validate it with Pillar II.
Expose minimum metadata design as a public repository.

## Why
In order to provide the minimum requirements for countries to connect to GDI - User Portal.

## Tasks
* Establish format of the document.
* Define who will contribute to that definition.
* Prepare the minimum metadata model.
* Discuss and present minimum metadata model.

**Comment by jambelien** [comment]
Started with an update of the description

**Comment by brunopacheco1** [comment]
@juankdiz also mentioned that any definition on that must come from 1+MG.

**Comment by jambelien** [comment]
<img width="464" alt="image" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-docs/assets/1975893/44e1f7da-0857-4807-a648-6628398a18e1">

Within 1+MG we use the sunflower metaphor: the core minimal dataset contains cross-specialty mandatory fields, the next layer inherits the mandatory fields of the core and adds mandatory fields specific for a domain or specialism. The outer layer (petals of sunflower) adds the problem/disease specific mandatory fields.
The same can be applied for the metadata scheme, where the core is DCAT-AP with a number of required/mandatory items, the next ring would then be (in the end) the Health DCAT-AP extension and petals the use case specific metadata schemes.

**Comment by jambelien** [comment]
<img width="1027" alt="Screenshot 2023-12-12 at 10 00 49" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-docs/assets/1975893/8ea00897-952d-4c3e-9e99-b0c2759d32de">

This picture shows the current state of the confirmed or still under development minimal datasets.

**Comment by jambelien** [comment]
<img width="1032" alt="Screenshot 2023-12-12 at 10 03 28" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-docs/assets/1975893/62deab2b-e735-4c79-a055-3af4b9126a58">

This picture shows the next steps (to be detailed).

**Comment by jambelien** [comment]
so indeed as you already suggested/pointed towards: we can start with the bare minimal metadata schema, the DCAT-AP core and next do the mapping and (potential) harmonisation between the current confirmed minimal datatsets and based on the result start designing the metadata petals for each use case.

**Comment by jambelien** [comment]
At Health-RI the DCAT-AP core has been designed, discussed and now confirmed and being implemented in the first MVP of the data catalog. We can take that as a starting point.

**Comment by brunopacheco1** [comment]
We should document this on gdi-userportal-docs, referring to 1+MG minimal dataset.

Although anyone with minimum knowledge should be able to follow DCAT-AP specs, perhaps we could be explicit regarding what are the mandatory fields, and even provide an example of harvestable RDF catalogue file.

Who can work on that documentation?
